/**
 * Every data-testid in the app. E2E tests select by role, accessible name or one of these IDs,
 * never by CSS classes (QA-05). The table in README.md is checked against this object.
 */
export const testIds = {
  tabLists: 'tab-lists',
  tabMeals: 'tab-meals',
  tabIngredients: 'tab-ingredients',
  tabMe: 'tab-me',
  screenLists: 'screen-lists',
  screenMeals: 'screen-meals',
  screenIngredients: 'screen-ingredients',
  screenMe: 'screen-me',
  languageSelect: 'language-select',
  appVersion: 'app-version',
  sourceLink: 'source-link',
  updatePrompt: 'update-prompt',
  screenLogin: 'screen-login',
  loginReason: 'login-reason',
  screenJoin: 'screen-join',
  screenReset: 'screen-reset',
  linkInvalid: 'link-invalid',
  displayNameInput: 'display-name-input',
  mealsPublicSwitch: 'meals-public-switch',
  listsPublicSwitch: 'lists-public-switch',
  coupleSection: 'couple-section',
  couplePartner: 'couple-partner',
  couplePicker: 'couple-picker',
  securityNotice: 'security-notice',
  changePasswordButton: 'change-password-button',
  sessionList: 'session-list',
  logoutAllButton: 'logout-all-button',
  adminEntry: 'admin-entry',
  logoutButton: 'logout-button',
  screenAdminUsers: 'screen-admin-users',
  adminUserList: 'admin-user-list',
  screenAdminInvites: 'screen-admin-invites',
  createInviteButton: 'create-invite-button',
  inviteList: 'invite-list',
  screenAdminEvents: 'screen-admin-events',
  eventList: 'event-list',
  shareLinkUrl: 'share-link-url',
  shareButton: 'share-button',
  hintHomeScreen: 'hint-home-screen',
  hintTailscale: 'hint-tailscale',
} as const;

export type TestId = (typeof testIds)[keyof typeof testIds];
